apiVersion: v1
kind: Service
metadata:
  labels:
    app: myphpadmin
  name: myphpadmin
spec:
  type: LoadBalancer
  ports:
    - port: 8580
      targetPort: 8580
      protocol: TCP
  selector:
    app: myphpadmin
